### ISSUE TITLE
中文部分字乱码，比如玥等

### ISSUE THREAD

**Issue by rmbzlib** [caoqianli/requests#3]
玥字等乱码，好像是和GBK、GB2312有关，设置charset和responseCharset编码依旧无法解决
怎么破

**Comment by GongLe** [comment]
Response<String> resp = Requests.get("http://127.0.0.1:8080")
                .charset(StandardCharsets.UTF_8).text();
换成=>  final Charset GBK = Charset.forName("GBK");
